### PR TITLE
CHORE: Fix es-lint padding warnings

### PR DESCRIPTION
**Pull request by simonmarklar**

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Should this also include re-enabling ESLint's rule in error mode?

**Comment by simonmarklar** [comment]
I was wondering how that would go. In this branch its the default, which is enabled as an error. 

I figure if i merge this pr in then i'd probably have to rebase the other pr to fix merge issues and i'll just remove the rule from that branch, as the other one is the only branch the rule has been demoted in.

**Comment by jokeyrhyme** [comment]
Ah okay. Yeah. I was confused. That makes sense. I want to merge this quick-smart as I can't be bothered with the gymnastics in my own branch. :P

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Pull request merged**
