### PR TITLE
BIC-197 # Unable to view a list of forms in any browser

### PR DESCRIPTION
**Pull request by simonmarklar**
- Removed use of XPath in favor of jquery
- Added helper function for subform processing
- added tests for helper function

### CODE REVIEW

**Comment by simonmarklar** [comment]
Tested using develop server pointing at `https://blinkm.co/simon/firstlevel_list` and opening add, edit, view and delete interactions on the following browsers:
*NOTE Testing on mac safari is needed!*

Windows
  - Chrome
  - Firefox
  - IE9
  - IE11
  - Edge

Android 5.0:
  - Chrome
  - mBaaS trial

iPad (iOS 8.2)
  - Safari
  - mBaaS

**Comment by jokeyrhyme** [comment]
Haha. I forgot to actually checkout the PR, but that's already working in OS X Safari 9 for me with whichever version of the BIC is selected.

**Comment by simonmarklar** [comment]
interesting. Ray showed me it failing with a console error on safari on his mac `Cannot call method trim of undefined` when evaluating `data.innerHTML.trim()` which is so weird because an empty div will return an empty string. It must be an XML quirk.

There was also a `cannot call method forEach of undefined` on the pending queue as well, perhaps the two are related.

however, XPath needed to be removed, the windows app would crash with the same problem IE11 had - document.execute and the XPath enums did not exist, and IE doesnt have `.innerHTML` property on XML nodes :(

I expect that this would work on safari for mac, but it would be awesome if someone with a mac could check

**Comment by jokeyrhyme** [comment]
Working fine for me in Safari 9 beta.

I did notice this odd double-enhancement though:
screen shot 2015-09-04 at 08 39 40
But that's nothing to do with this PR.

**Comment by jokeyrhyme** [comment]
LGTM :+1: 

We should probably update the handful of Forms tests that work with record XML, too.

**Comment by simonmarklar** [comment]
the double enhancement already has a ticket in FORMS-228

re: the forms tests, a cursory glance shows they do use xpath, this would only effect test run on ie (which means, karma on my machine ha!) so i'll raise a minor ticket for that. 

I just did a quick check of the XSLT code, that seems to be ok, using the IE  `transformNode` function rather than `XSLTProcessor`. phew.

UX review by ray yesterday.

good to merge ?

**Pull request merged**
