### PR TITLE
BIC-255 # dismiss native splash screen after first interaction loaded

### PR DESCRIPTION
**Pull request by GeetaSajwan**
BIC-255 dismiss native splash screen after first interaction loaded

- created middleware for the purpose.
- created tests

### CODE REVIEW

**Comment by simonmarklar** [comment]
lgtm :+1:

**Comment by jokeyrhyme** [comment]
Can you add a test where you call it twice, and confirm that the call count is still 1?

**Comment by simonmarklar** [comment]
unless i read it wrong, it is called twice, the `next()` function is another call to the middleware

**Comment by jokeyrhyme** [comment]
If we call the middleware twice, then `next()` should be called twice. However, the BootStatus part should only run once.

**Comment by jokeyrhyme** [comment]
So, if it's possible to write such a test, then the test should count the number of times BootStatus is called, and it might be nice to also count the number of times that `next()` is called.

**Comment by simonmarklar** [comment]
the test defines a spy for bootstatus, then calls the middleware passing in a function that does a second call to middleware as the `next` route. The second middleware calls `next` function verifies that the bootstatus spy was called once and calls done. Does that not do exactly what you are asking for ?

**Comment by jokeyrhyme** [comment]
Quite right. My bad.
LGTM :+1:

**Pull request merged**
