### PR TITLE
BIC-231 # Home interaction setting is now honored in the middleware

### PR DESCRIPTION
**Pull request by simonmarklar**

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Ah! Wow, it's embarrassing that I missed that. :)

One day we should find a more descriptive name for `#prepareForView()`. :P

LGTM :+1:

**Comment by simonmarklar** [comment]
I wouldnt be embarrased, I think that you missed it because prepareForView shouldnt be doing what it is. I had to step through the code bit by bit to figure out what was going on, its un intuitive. That stuff should be figured out earlier than it is... i think we need to rework that code path

**Comment by jokeyrhyme** [comment]
I'm hoping the new middleware approach is worth the extra complexity, especially for upcoming refactoring and authentication rework.

**Comment by simonmarklar** [comment]
ux review from sam

**Pull request merged**
