### PR TITLE
Feature/fs changes

### PR DESCRIPTION
**Pull request by ashishtilara**
moved model/view/collections to different folders

### CODE REVIEW

**Comment by simonmarklar** [comment]
LGTM

**Comment by simonmarklar** [comment]
Travis doesnt want to launch chrome eh...

**Comment by jokeyrhyme** [comment]
LGTM. However, I wonder if it's worth following the same pattern as with Forms where we now have `'forms/jqm'` instead of the previous `'forms/view/jqm'`? How about using `'bic/jqm'` here?
The downside is that module consumers need to know that they're using the jQM version. The upside is that it's easier to maintain different view implementations. Are there any other drawbacks?

**Comment by jokeyrhyme** [comment]
@ashishtilara looks like this needs merging / rebasing to deal with conflicts with the recent PRs...

**Comment by ashishtilara** [comment]
idk we can... but since we have made lot of change after that, we either resolve all conflicts and change views to `bic/jqm`, but then again templates are in templates folder so what to do with that..?!

**Comment by jokeyrhyme** [comment]
Yeah, that's tricky. Templates are really view-implementation specific. So I guess they'd be `'bic/jqm/templates/...'` which seems a bit long. /shrug

**Comment by jokeyrhyme** [comment]
I figured I'd just think out loud. I don't have any blocking concerns with this restructure.
Can you check out the merge conflicts, pretty please? :)

**Comment by ashishtilara** [comment]
done :+1:

**Pull request merged**
