### PR TITLE
BIC-208 # Basic login interactions dont work with windows app

### PR DESCRIPTION
**Pull request by simonmarklar**
- Added path parser to normalise url path across cordova and browsers
- Added tests

### CODE REVIEW

**Comment by simonmarklar** [comment]
Tested on

Windows
- Chrome
- FF
- Edge
- IE9
- IE11
- Windows App made with cordova

Android 5
- mBaaS Trial
- Chrome
- Appshell made with Cordova

iOS
- mBaaS Trial
- safari

**Comment by jokeyrhyme** [comment]
LGTM :+1: 
Impressive test coverage there, too. :D

**Comment by simonmarklar** [comment]
i spent more time trying to figure out what the iOS url was for testing than I did writing the fix, as its the one platform that I cant build for :warning: 

Im still not sure the iOS prefix is correct, but the regex should catch any cordova url though, as the /www/index.html part seems to universal

**Comment by simonmarklar** [comment]
UX Review From Rachel :+1: 

also tested on Windows 8.1 tablet

**Pull request merged**
