### PR TITLE
added link to jquery mobile issue that explains what is going on and …

### PR DESCRIPTION
**Pull request by simonmarklar**

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
LGTM :+1:

**Comment by jokeyrhyme** [comment]
@simonmarklar looks like this needs merging / rebasing to clear some conflicts with the recent PRs...

**Comment by simonmarklar** [comment]
I actually think this doesnt need to be done anymore - the error summary is only shown when you try to go forward a page or submit - its not shown on page open anymore

**Comment by simonmarklar** [comment]
The changes are no  longer necessary due to changes in BIC-174 which prevent errors from being enhanced while page is loading.

**Pull request closed without merging**
