### PR TITLE
BIC-164 - Fixed spelling mistake preventing kml maps from working

### PR DESCRIPTION
**Pull request by simonmarklar**
Capital 'M' to lower case 'm' makes case sensitive things happy.

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Is there a way to fix the place where this is called instead?
Idiomatic JavaScript would suggest that functions with capital letters can be expected to be constructors, and this is not a constructor.

**Comment by simonmarklar** [comment]
I'm not sure i follow you, I changed it from upper to lower. 

It's a callback function used by google maps. it's a pointer to a function that starts with a lower case letter. it was an upper case M, as opposed to the 3 other places the callback is  set, so i made it lower case.

**Comment by jokeyrhyme** [comment]
Oh, I misread the diff. My bad. Yes, starting with lower case in this case is great and you've done that. Cheers.

**Comment by jokeyrhyme** [comment]
LGTM. :)

**Pull request merged**
